package pt.uc.dei.paj.general;

public enum NotificationType {
	N1_APPROVEPROJECTMEMBER, N2_REJECTPROJECTMEMBER, N3_REQUESTTOBEPROJECTMEMBER, N4_INVITEUSERTOBEINPROJECT,
	N5_ACCEPTUSERINVITATION, N6_DECLINEUSERINVITATION
}
